version: '3'

networks:
  dev:

services:
#  nginx:
#    image: nginx:stable-alpine
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - './nginx.conf:/etc/nginx/nginx.conf'
#      - /etc/letsencrypt/live/betulla-cosmetics.ru/fullchain.pem:/etc/letsencrypt/live/betulla-cosmetics.ru/fullchain.pem
#      - /etc/letsencrypt/live/betulla-cosmetics.ru/privkey.pem:/etc/letsencrypt/live/betulla-cosmetics.ru/privkey.pem
#
#    depends_on:
#      - payload
#      - frontend
#    networks:
#      - dev


  frontend:
    container_name: frontend
#    build:
#      context: ./frontend
    networks:
      - dev
    ports:
      - "80:80"
    env_file:
      - .env

volumes:
  node_modules:
